services:
- type: web
  name: bingo
  env: docker
  autoDeploy: true
  healthCheckPath: /api/healthz
  plan: free
  envVars:
  - key: BING_UA
    value: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.0.0
  - key: BING_COOKIE
    value:
  - key: PORT
    value: 10000
